palette = 'catppuccin_macchiato'

format = """
$cmd_duration\
$line_break\
$username\
$character\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
"""
right_format="""
$git_state\
$time\
"""
add_newline = false

[palettes.catppuccin_macchiato]
rosewater = '#f4dbd6'
flamingo = '#f0c6c6'
pink = '#f5bde6'
mauve = '#c6a0f6'
red = '#ed8796'
maroon = '#ee99a0'
peach = '#f5a97f'
yellow = '#eed49f'
green = '#a6da95'
teal = '#8bd5ca'
sky = '#91d7e3'
sapphire = '#7dc4e4'
blue = '#8aadf4'
lavender = '#b7bdf8'
text = '#cad3f5'
subtext1 = '#b8c0e0'
subtext0 = '#a5adcb'
overlay2 = '#939ab7'
overlay1 = '#8087a2'
overlay0 = '#6e738d'
surface2 = '#5b6078'
surface1 = '#494d64'
surface0 = '#363a4f'
base = '#24273a'
mantle = '#1e2030'
crust = '#181926'


[character]
format = '$symbol  '
success_symbol = '[](bold green)'
error_symbol = '[✘](bold red)'

[username]
style_user = 'bold blue'
show_always = true
format = '[$user]($style) '

[directory]
format = '[$read_only]($read_only_style)[$path ]($style)'
style = 'bold teal'
home_symbol = ' '
read_only = ' '
repo_root_style = 'yellow'
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
style = 'bold sky'
truncation_length = 8
symbol = ' '
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]

[git_status]
ahead = '[⇡${count}](bold green)'
diverged = '⇕[⇡${ahead_count}](bold green)[⇣${behind_count}](bold red))'
behind = '[⇣${count}](bold red)'

[git_metrics]
disabled = false

[time]
disabled = false
format = '[$time]($style)'
time_format = '%R'
style = 'bold surface2'

[line_break]
disabled = false

[cmd_duration]
format = '[took $duration]($style) '
min_time = 1_000
show_notifications = true
notification_timeout = 15_000
style = 'bold overlay0'
